version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - pnpm install --prod
      - pnpm build

artifacts:
  files:
    - '**/*'
  name: chatter-build-artifacts
